spring.application.name=Elite-Gym
spring.profiles.active=dev

integration.service.url=http://integration-service/integration/events
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
internal.api.secret=gym-erp-internal-secret-key-2024
